#!/bin/bash

echo "📊 Accès à la base de données SQLite :"
echo ""
echo "🔹 Option A - Via l'administration Django :"
echo "   http://localhost:8000/admin/"
echo "   Login: admin / Mot de passe: admin123"
echo ""
echo "🔹 Option B - Navigateur de fichiers SQLite :"
echo "   1. Ouvrez : https://sqliteviewer.app/"
echo "   2. Téléchargez le fichier : $(pwd)/db.sqlite3"
echo "   3. Uploadez-le sur le site"
echo ""
echo "🔹 Option C - En ligne de commande :"
echo "   sqlite3 $(pwd)/db.sqlite3"
echo "   Puis: .tables"
echo "        SELECT * FROM app_core_specialite;"
echo ""
echo "🔹 Option D - Outil local :"
echo "   Installer DB Browser for SQLite ou DBeaver"