#!/bin/bash

echo "🚀 CONFIGURATION MONGODB POUR L'APPLICATION DJANGO ENISE"
echo "======================================================="
echo ""
echo "📋 Installation et configuration terminées :"
echo ""
echo "✅ Dépendances installées :"
echo "   - pymongo (connecteur Python MongoDB)"
echo "   - mongoengine (ODM MongoDB)" 
echo "   - djongo (bridge Django-MongoDB)"
echo ""
echo "🗄️ Configuration MongoDB :"
echo "   - Base de données : enise_db (via djongo)"
echo "   - Base de fichiers : enise_filesystem (via mongoengine)"
echo "   - GridFS activé pour le stockage de fichiers"
echo ""
echo "🔧 Fonctionnalités implémentées :"
echo "   - Upload de fichiers avec drag & drop"
echo "   - Gestion des permissions (public/privé)"
echo "   - Journalisation des accès"
echo "   - Système de tags et catégories"
echo "   - Interface web responsive"
echo ""
echo "🌐 URLs ajoutées :"
echo "   - /files/ : Gestionnaire de fichiers principal"
echo "   - /files/upload/ : Upload de fichiers"
echo "   - /files/<id>/download/ : Téléchargement"
echo "   - /files/<id>/details/ : Détails du fichier"
echo "   - /files/logs/ : Logs d'accès"
echo ""
echo "⚠️  IMPORTANT :"
echo "   - Assurez-vous que MongoDB est installé et démarré"
echo "   - Commande pour démarrer MongoDB : sudo systemctl start mongod"
echo "   - Le serveur doit être redémarré pour prendre en compte les changements"
echo ""
echo "🔗 Accès à l'application :"
echo "   - Site principal : http://localhost:8000/"
echo "   - Gestionnaire de fichiers : http://localhost:8000/files/"
echo "   - Admin Django : http://localhost:8000/admin/"
echo "   - Login admin : admin / admin123"
echo ""
echo "📊 Collections MongoDB créées :"
echo "   - file_metadata : Métadonnées des fichiers"
echo "   - fs.files : Fichiers stockés (GridFS)"
echo "   - fs.chunks : Chunks de fichiers (GridFS)"
echo "   - file_access_logs : Journal d'accès"
echo "   - user_permissions : Permissions utilisateurs"