#!/bin/bash

echo "🧪 TEST DU GESTIONNAIRE DE FICHIERS"
echo "==================================="
echo ""
echo "✅ Serveur Django fonctionnel :"
echo "   • Page d'accueil : $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/)"
echo "   • Page login : $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/login/)"
echo "   • Gestionnaire fichiers : $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/files/)"
echo "   • Admin Django : $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/admin/)"
echo ""
echo "🔐 Pour tester l'upload de fichiers :"
echo "   1. Allez sur http://localhost:8000/login/"
echo "   2. Connectez-vous avec admin/admin123"
echo "   3. Accédez à http://localhost:8000/files/"
echo "   4. Cliquez sur 'Uploader un fichier'"
echo ""
echo "📁 Fichiers de test créés :"
echo "   • test_upload.txt (fichier texte de test)"
echo "   • Dossier de stockage : $(ls -la media/uploads/ 2>/dev/null || echo 'Non encore créé')"
echo ""
echo "⚠️  Si erreur d'upload :"
echo "   • Vérifiez les logs : tail -f django_server.log"
echo "   • Le système utilise un stockage local (pas MongoDB)"
echo "   • Les fichiers sont sauvegardés dans media/uploads/"
echo ""
echo "🎯 L'application est prête à l'emploi !"